"""removed week columns

Revision ID: 2e1dd7307f9f
Revises: b9bbfcb5aadb
Create Date: 2024-12-02 10:26:10.659173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e1dd7307f9f'
down_revision = 'b9bbfcb5aadb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timesheet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_days', sa.String(length=80), nullable=True))
        batch_op.drop_column('week1')
        batch_op.drop_column('week3')
        batch_op.drop_column('week2')
        batch_op.drop_column('week4')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timesheet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('week4', sa.VARCHAR(length=40), nullable=True))
        batch_op.add_column(sa.Column('week2', sa.VARCHAR(length=40), nullable=True))
        batch_op.add_column(sa.Column('week3', sa.VARCHAR(length=40), nullable=True))
        batch_op.add_column(sa.Column('week1', sa.VARCHAR(length=40), nullable=True))
        batch_op.drop_column('selected_days')

    # ### end Alembic commands ###
