"""add man_id

Revision ID: 2f6759e8b198
Revises: 2e1dd7307f9f
Create Date: 2024-12-02 15:41:56.720388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f6759e8b198'
down_revision = '2e1dd7307f9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timesheet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('man_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_timesheet_manager', 'manager', ['man_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timesheet', schema=None) as batch_op:
        batch_op.drop_constraint('fk_timesheet_manager', type_='foreignkey')
        batch_op.drop_column('man_id')

    # ### end Alembic commands ###
