"""added foreign key names

Revision ID: 69cc159e9440
Revises: 59bffd3294c5
Create Date: 2024-11-19 20:25:01.934243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69cc159e9440'
down_revision = '59bffd3294c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_employee_manager', 'manager', ['manager_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint('fk_employee_manager', type_='foreignkey')
        batch_op.drop_column('manager_id')

    # ### end Alembic commands ###
