"""Initial Migration

Revision ID: d59ac76bc777
Revises: 
Create Date: 2024-11-19 19:16:06.961206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd59ac76bc777'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('manager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('timesheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=15), nullable=False),
    sa.Column('year', sa.String(length=4), nullable=False),
    sa.Column('week1', sa.String(length=40), nullable=False),
    sa.Column('week2', sa.String(length=40), nullable=False),
    sa.Column('week3', sa.String(length=40), nullable=False),
    sa.Column('week4', sa.String(length=40), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timesheet')
    op.drop_table('manager')
    op.drop_table('employee')
    # ### end Alembic commands ###
